name: nito

packages:
  - core/**
  - data/**
  - feature/**
  - frontend

sdk_path: .fvm/flutter_sdk

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  feature:build_runner:build:
    run: |
      melos exec -- \
        "fvm flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run a build_runner build in the features.
    select-package:
      scope: '*feature*'
      ignore:
        - '*example*'
