name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: macos-12

    steps:
      - name: checkout
        uses: actions/checkout@v3

      # 本番環境用の .env を作成
      - name: create .env
        run: |
          touch .env
          echo SUPABASE_URL=${{secrets.SUPABASE_URL}} >> .env
          echo SUPABASE_ANON_KEY=${{secrets.SUPABASE_ANON_KEY}} >> .env
        working-directory: ./apps/frontend

      # asdf と .tool-versions に記載してある flutter をインストール
      # https://github.com/asdf-vm/actions#main-actions
      - name: install asdf and flutter plugin
        uses: asdf-vm/actions/install@v1

      # Melos をインストール
      - name: install melos
        run: |
          dart pub global activate melos
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          melos bootstrap

      # Web ビルドを実行
      - name: web build
        run: flutter build web
        working-directory: ./apps/frontend

      # Firebase Hosting にデプロイ
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWORABS_NITO }}'
          projectId: tworabs-nito
