name: Migrations to Production

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  migrate_supabase_database:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      PROJECT_ID: hwxxihvcszfhaxlguajv

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: |
          supabase link --project-ref $PROJECT_ID
          supabase db push
